//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the vehicle_controller package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __vehicle_controller__PDPARAMSARGOCONFIG_H__
#define __vehicle_controller__PDPARAMSARGOCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace vehicle_controller
{
  class PdParamsArgoConfigStatics;
  
  class PdParamsArgoConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PdParamsArgoConfig &config, const PdParamsArgoConfig &max, const PdParamsArgoConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PdParamsArgoConfig &config1, const PdParamsArgoConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PdParamsArgoConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PdParamsArgoConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PdParamsArgoConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PdParamsArgoConfig &config) const = 0;
      virtual void getValue(const PdParamsArgoConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PdParamsArgoConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PdParamsArgoConfig::* field);

      virtual void clamp(PdParamsArgoConfig &config, const PdParamsArgoConfig &max, const PdParamsArgoConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PdParamsArgoConfig &config1, const PdParamsArgoConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PdParamsArgoConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PdParamsArgoConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PdParamsArgoConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PdParamsArgoConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PdParamsArgoConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PdParamsArgoConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PdParamsArgoConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PdParamsArgoConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PdParamsArgoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("angle_p_gain"==(*_i)->name){angle_p_gain = boost::any_cast<double>(val);}
        if("angle_d_gain"==(*_i)->name){angle_d_gain = boost::any_cast<double>(val);}
        if("position_p_gain"==(*_i)->name){position_p_gain = boost::any_cast<double>(val);}
        if("position_d_gain"==(*_i)->name){position_d_gain = boost::any_cast<double>(val);}
        if("speed"==(*_i)->name){speed = boost::any_cast<double>(val);}
        if("speed_reduction_gain"==(*_i)->name){speed_reduction_gain = boost::any_cast<double>(val);}
        if("use_final_twist"==(*_i)->name){use_final_twist = boost::any_cast<bool>(val);}
        if("final_twist_trials_max"==(*_i)->name){final_twist_trials_max = boost::any_cast<int>(val);}
        if("flipper_low_position"==(*_i)->name){flipper_low_position = boost::any_cast<double>(val);}
        if("flipper_high_position"==(*_i)->name){flipper_high_position = boost::any_cast<double>(val);}
        if("flipper_switch_position"==(*_i)->name){flipper_switch_position = boost::any_cast<double>(val);}
      }
    }

    double angle_p_gain;
double angle_d_gain;
double position_p_gain;
double position_d_gain;
double speed;
double speed_reduction_gain;
bool use_final_twist;
int final_twist_trials_max;
double flipper_low_position;
double flipper_high_position;
double flipper_switch_position;

    bool state;
    std::string name;

    
}groups;



//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_p_gain;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_d_gain;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_p_gain;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_d_gain;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double speed;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double speed_reduction_gain;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_final_twist;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int final_twist_trials_max;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double flipper_low_position;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double flipper_high_position;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double flipper_switch_position;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PdParamsArgoConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PdParamsArgoConfig &__max__ = __getMax__();
      const PdParamsArgoConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PdParamsArgoConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PdParamsArgoConfig &__getDefault__();
    static const PdParamsArgoConfig &__getMax__();
    static const PdParamsArgoConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const PdParamsArgoConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PdParamsArgoConfig::ParamDescription<std::string>::clamp(PdParamsArgoConfig &config, const PdParamsArgoConfig &max, const PdParamsArgoConfig &min) const
  {
    return;
  }

  class PdParamsArgoConfigStatics
  {
    friend class PdParamsArgoConfig;
    
    PdParamsArgoConfigStatics()
    {
PdParamsArgoConfig::GroupDescription<PdParamsArgoConfig::DEFAULT, PdParamsArgoConfig> Default("Default", "", 0, 0, true, &PdParamsArgoConfig::groups);
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_p_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_p_gain = 100.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_p_gain = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("angle_p_gain", "double", 0, "P gain 4 angle control in differential drive controller", "", &PdParamsArgoConfig::angle_p_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("angle_p_gain", "double", 0, "P gain 4 angle control in differential drive controller", "", &PdParamsArgoConfig::angle_p_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_d_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_d_gain = 100.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_d_gain = 0.5;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("angle_d_gain", "double", 0, "D gain 4 angle control in differential drive controller", "", &PdParamsArgoConfig::angle_d_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("angle_d_gain", "double", 0, "D gain 4 angle control in differential drive controller", "", &PdParamsArgoConfig::angle_d_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_p_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_p_gain = 100.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_p_gain = 0.5;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("position_p_gain", "double", 0, "P gain 4 position control in differential drive controller", "", &PdParamsArgoConfig::position_p_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("position_p_gain", "double", 0, "P gain 4 position control in differential drive controller", "", &PdParamsArgoConfig::position_p_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_d_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_d_gain = 100.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_d_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("position_d_gain", "double", 0, "D gain 4 position control in differential drive controller", "", &PdParamsArgoConfig::position_d_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("position_d_gain", "double", 0, "D gain 4 position control in differential drive controller", "", &PdParamsArgoConfig::position_d_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed = 0.075;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("speed", "double", 0, "Desired speed 4 position control in differential drive controller", "", &PdParamsArgoConfig::speed)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("speed", "double", 0, "Desired speed 4 position control in differential drive controller", "", &PdParamsArgoConfig::speed)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed_reduction_gain = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed_reduction_gain = 100.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed_reduction_gain = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("speed_reduction_gain", "double", 0, "Gain to control the linear speed reduction for rising angular rate", "", &PdParamsArgoConfig::speed_reduction_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("speed_reduction_gain", "double", 0, "Gain to control the linear speed reduction for rising angular rate", "", &PdParamsArgoConfig::speed_reduction_gain)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_final_twist = 0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_final_twist = 1;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_final_twist = 1;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<bool>("use_final_twist", "bool", 0, "Flag determining if orientation is corrected at the end of a path", "", &PdParamsArgoConfig::use_final_twist)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<bool>("use_final_twist", "bool", 0, "Flag determining if orientation is corrected at the end of a path", "", &PdParamsArgoConfig::use_final_twist)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.final_twist_trials_max = 0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.final_twist_trials_max = 2000;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.final_twist_trials_max = 200;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<int>("final_twist_trials_max", "int", 0, "Maximum number of control trials for final position approach", "", &PdParamsArgoConfig::final_twist_trials_max)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<int>("final_twist_trials_max", "int", 0, "Maximum number of control trials for final position approach", "", &PdParamsArgoConfig::final_twist_trials_max)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.flipper_low_position = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.flipper_low_position = 0.75;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.flipper_low_position = 0.1;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_low_position", "double", 0, "Low position of the flippers for driving", "", &PdParamsArgoConfig::flipper_low_position)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_low_position", "double", 0, "Low position of the flippers for driving", "", &PdParamsArgoConfig::flipper_low_position)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.flipper_high_position = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.flipper_high_position = 0.75;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.flipper_high_position = 0.4;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_high_position", "double", 0, "High position of the flippers for driving", "", &PdParamsArgoConfig::flipper_high_position)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_high_position", "double", 0, "High position of the flippers for driving", "", &PdParamsArgoConfig::flipper_high_position)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.flipper_switch_position = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.flipper_switch_position = 0.75;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.flipper_switch_position = 0.25;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_switch_position", "double", 0, "Flipper toggle command: set to high position if its below this value, else to the low", "", &PdParamsArgoConfig::flipper_switch_position)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PdParamsArgoConfig::AbstractParamDescriptionConstPtr(new PdParamsArgoConfig::ParamDescription<double>("flipper_switch_position", "double", 0, "Flipper toggle command: set to high position if its below this value, else to the low", "", &PdParamsArgoConfig::flipper_switch_position)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PdParamsArgoConfig::AbstractGroupDescriptionConstPtr(new PdParamsArgoConfig::GroupDescription<PdParamsArgoConfig::DEFAULT, PdParamsArgoConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PdParamsArgoConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<PdParamsArgoConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PdParamsArgoConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PdParamsArgoConfig __max__;
    PdParamsArgoConfig __min__;
    PdParamsArgoConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PdParamsArgoConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PdParamsArgoConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PdParamsArgoConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PdParamsArgoConfig &PdParamsArgoConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PdParamsArgoConfig &PdParamsArgoConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PdParamsArgoConfig &PdParamsArgoConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PdParamsArgoConfig::AbstractParamDescriptionConstPtr> &PdParamsArgoConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PdParamsArgoConfig::AbstractGroupDescriptionConstPtr> &PdParamsArgoConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PdParamsArgoConfigStatics *PdParamsArgoConfig::__get_statics__()
  {
    const static PdParamsArgoConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PdParamsArgoConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PDPARAMSARGORECONFIGURATOR_H__
