set(_CATKIN_CURRENT_PACKAGE "eng_control")
set(eng_control_VERSION "0.0.0")
set(eng_control_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(eng_control_PACKAGE_FORMAT "1")
set(eng_control_BUILD_DEPENDS )
set(eng_control_BUILD_EXPORT_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(eng_control_BUILDTOOL_DEPENDS "catkin")
set(eng_control_BUILDTOOL_EXPORT_DEPENDS )
set(eng_control_EXEC_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(eng_control_RUN_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(eng_control_TEST_DEPENDS )
set(eng_control_DOC_DEPENDS )
set(eng_control_DEPRECATED "")