// Generated by gencpp from file motion_editor_core/ExecuteMotionFeedback.msg
// DO NOT EDIT!


#ifndef MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONFEEDBACK_H
#define MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_editor_core
{
template <class ContainerAllocator>
struct ExecuteMotionFeedback_
{
  typedef ExecuteMotionFeedback_<ContainerAllocator> Type;

  ExecuteMotionFeedback_()
    {
    }
  ExecuteMotionFeedback_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMotionFeedback_

typedef ::motion_editor_core::ExecuteMotionFeedback_<std::allocator<void> > ExecuteMotionFeedback;

typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionFeedback > ExecuteMotionFeedbackPtr;
typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionFeedback const> ExecuteMotionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_editor_core

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motion_editor_core': ['/home/somal/catkin_ws/src/motion_editor/motion_editor_core/msg', '/home/somal/catkin_ws/devel/share/motion_editor_core/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_editor_core/ExecuteMotionFeedback";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
\n\
\n\
";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ExecuteMotionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::motion_editor_core::ExecuteMotionFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONFEEDBACK_H
