// Generated by gencpp from file motion_editor_core/ExecuteMotionAction.msg
// DO NOT EDIT!


#ifndef MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONACTION_H
#define MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <motion_editor_core/ExecuteMotionActionGoal.h>
#include <motion_editor_core/ExecuteMotionActionResult.h>
#include <motion_editor_core/ExecuteMotionActionFeedback.h>

namespace motion_editor_core
{
template <class ContainerAllocator>
struct ExecuteMotionAction_
{
  typedef ExecuteMotionAction_<ContainerAllocator> Type;

  ExecuteMotionAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ExecuteMotionAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
    }



   typedef  ::motion_editor_core::ExecuteMotionActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::motion_editor_core::ExecuteMotionActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::motion_editor_core::ExecuteMotionActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;




  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMotionAction_

typedef ::motion_editor_core::ExecuteMotionAction_<std::allocator<void> > ExecuteMotionAction;

typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionAction > ExecuteMotionActionPtr;
typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionAction const> ExecuteMotionActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_editor_core

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motion_editor_core': ['/home/somal/catkin_ws/src/motion_editor/motion_editor_core/msg', '/home/somal/catkin_ws/devel/share/motion_editor_core/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e654473e74e04ab9739bbe3f0750779";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e654473e74e04abULL;
  static const uint64_t static_value2 = 0x9739bbe3f0750779ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_editor_core/ExecuteMotionAction";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
ExecuteMotionActionGoal action_goal\n\
ExecuteMotionActionResult action_result\n\
ExecuteMotionActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
ExecuteMotionGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
string motion_name\n\
float32 time_factor\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
ExecuteMotionResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result\n\
int32[] error_code\n\
int32 SUCCESSFUL = 0\n\
int32 INVALID_GOAL = -1\n\
int32 INVALID_JOINTS = -2\n\
int32 OLD_HEADER_TIMESTAMP = -3\n\
int32 PATH_TOLERANCE_VIOLATED = -4\n\
int32 GOAL_TOLERANCE_VIOLATED = -5\n\
int32 MOTION_UNKNOWN = -6\n\
\n\
string error_string\n\
string[] error_group\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
ExecuteMotionFeedback feedback\n\
\n\
================================================================================\n\
MSG: motion_editor_core/ExecuteMotionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
\n\
\n\
";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ExecuteMotionAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_editor_core::ExecuteMotionAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::motion_editor_core::ExecuteMotionActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::motion_editor_core::ExecuteMotionActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::motion_editor_core::ExecuteMotionActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONACTION_H
