// Generated by gencpp from file motion_editor_core/ExecuteMotion.msg
// DO NOT EDIT!


#ifndef MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTION_H
#define MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTION_H

#include <ros/service_traits.h>


#include <motion_editor_core/ExecuteMotionRequest.h>
#include <motion_editor_core/ExecuteMotionResponse.h>


namespace motion_editor_core
{

struct ExecuteMotion
{

typedef ExecuteMotionRequest Request;
typedef ExecuteMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteMotion
} // namespace motion_editor_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_editor_core::ExecuteMotion > {
  static const char* value()
  {
    return "df0966c07354a91b75525ffbd3ff4e08";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotion&) { return value(); }
};

template<>
struct DataType< ::motion_editor_core::ExecuteMotion > {
  static const char* value()
  {
    return "motion_editor_core/ExecuteMotion";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotion&) { return value(); }
};


// service_traits::MD5Sum< ::motion_editor_core::ExecuteMotionRequest> should match 
// service_traits::MD5Sum< ::motion_editor_core::ExecuteMotion > 
template<>
struct MD5Sum< ::motion_editor_core::ExecuteMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_editor_core::ExecuteMotion >::value();
  }
  static const char* value(const ::motion_editor_core::ExecuteMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_editor_core::ExecuteMotionRequest> should match 
// service_traits::DataType< ::motion_editor_core::ExecuteMotion > 
template<>
struct DataType< ::motion_editor_core::ExecuteMotionRequest>
{
  static const char* value()
  {
    return DataType< ::motion_editor_core::ExecuteMotion >::value();
  }
  static const char* value(const ::motion_editor_core::ExecuteMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_editor_core::ExecuteMotionResponse> should match 
// service_traits::MD5Sum< ::motion_editor_core::ExecuteMotion > 
template<>
struct MD5Sum< ::motion_editor_core::ExecuteMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_editor_core::ExecuteMotion >::value();
  }
  static const char* value(const ::motion_editor_core::ExecuteMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_editor_core::ExecuteMotionResponse> should match 
// service_traits::DataType< ::motion_editor_core::ExecuteMotion > 
template<>
struct DataType< ::motion_editor_core::ExecuteMotionResponse>
{
  static const char* value()
  {
    return DataType< ::motion_editor_core::ExecuteMotion >::value();
  }
  static const char* value(const ::motion_editor_core::ExecuteMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTION_H
