// Generated by gencpp from file motion_editor_core/ExecuteMotionResponse.msg
// DO NOT EDIT!


#ifndef MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONRESPONSE_H
#define MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Time.h>

namespace motion_editor_core
{
template <class ContainerAllocator>
struct ExecuteMotionResponse_
{
  typedef ExecuteMotionResponse_<ContainerAllocator> Type;

  ExecuteMotionResponse_()
    : ok(false)
    , finish_time()  {
    }
  ExecuteMotionResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , finish_time(_alloc)  {
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef  ::std_msgs::Time_<ContainerAllocator>  _finish_time_type;
  _finish_time_type finish_time;




  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMotionResponse_

typedef ::motion_editor_core::ExecuteMotionResponse_<std::allocator<void> > ExecuteMotionResponse;

typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionResponse > ExecuteMotionResponsePtr;
typedef boost::shared_ptr< ::motion_editor_core::ExecuteMotionResponse const> ExecuteMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_editor_core

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'motion_editor_core': ['/home/somal/catkin_ws/src/motion_editor/motion_editor_core/msg', '/home/somal/catkin_ws/devel/share/motion_editor_core/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc46ec169a534a83d0df8dab4f9cea97";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc46ec169a534a83ULL;
  static const uint64_t static_value2 = 0xd0df8dab4f9cea97ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_editor_core/ExecuteMotionResponse";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool ok\n\
\n\
std_msgs/Time finish_time\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Time\n\
time data\n\
";
  }

  static const char* value(const ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.finish_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ExecuteMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_editor_core::ExecuteMotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "finish_time: ";
    s << std::endl;
    Printer< ::std_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.finish_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_EDITOR_CORE_MESSAGE_EXECUTEMOTIONRESPONSE_H
