(cl:defpackage hector_move_base_msgs-msg
  (:use )
  (:export
   "<MOVEBASEACTIONGOAL>"
   "MOVEBASEACTIONGOAL"
   "<MOVEBASEEXPLORE>"
   "MOVEBASEEXPLORE"
   "<MOVEBASEACTIONRESULT>"
   "MOVEBASEACTIONRESULT"
   "<MOVEBASEPATH>"
   "MOVEBASEPATH"
   "<MOVEBASEGOAL>"
   "MOVEBASEGOAL"
   "<MOVEBASERESULT>"
   "MOVEBASERESULT"
   "<MOVEBASEFEEDBACK>"
   "MOVEBASEFEEDBACK"
   "<MOVEBASEACTIONFEEDBACK>"
   "MOVEBASEACTIONFEEDBACK"
   "<MOVEBASEACTION>"
   "MOVEBASEACTION"
   "<MOVEBASEACTIONPATH>"
   "MOVEBASEACTIONPATH"
   "<MOVEBASEACTIONEXPLORE>"
   "MOVEBASEACTIONEXPLORE"
   "<MOVEBASEACTIONGENERIC>"
   "MOVEBASEACTIONGENERIC"
  ))

