rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}


  joint3_controller:
    type: effort_controllers/JointEffortController
    joint: joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_controller:
    type: effort_controllers/JointEffortController
    joint: joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint5_controller:
    type: effort_controllers/JointEffortController
    joint: joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_controller:
    type: effort_controllers/JointEffortController
    joint: joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint7_controller:
    type: effort_controllers/JointEffortController
    joint: joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint8_controller:
    type: effort_controllers/JointPositionController
    joint: joint8
    pid: {p: 100.0, i: 0.01, d: 10.0}
