<?xml version="1.0" encoding="UTF-8"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415"/>
  <xacro:property name="mass" value="1" />
  <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0" />
  <!-- Square dimensions (widthxwidth) of beams  0.1-->
  <xacro:property name="height1" value="0" />
  <!-- Link 1 2  -->
  <xacro:property name="height2" value="0" />
  <!-- Link 2 1  -->
  <xacro:property name="height3" value="0" />
  <!-- Link 3 1 -->
  <xacro:property name="camera_link" value="0.05" />
  <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" />
  <!-- Space btw top of beam and the each joint -->
  <xacro:property name="base_link_size_x" value="0.1789" />
  <!--was 0.397-->
  <xacro:property name="base_link_size_y" value="0.397" />
  <!--was 0.1789-->
  <xacro:property name="base_link_size_z" value="${2*wheel_radius-ground_clearance}" />
  <!-- old 0.102 is double radius without ground_clearance 0.07683 -->
  <xacro:property name="wheel_radius"   value="0.051" />
  <!--was 0.09-->
  <xacro:property name="ground_clearance" value="0.02517" />
  <!--old 0.05 0.02517-->
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0 "/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/base_link2.dae"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/base_link2.dae"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 ${-base_link_size_y*0.5} 0" rpy="0 0 0 "/>
      <mass value="${5*mass}"/>
      <inertia	  ixx="1" ixy="0.0" ixz="0.0"	  iyy="1" iyz="0.0"	  izz="1"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="left_flipper"/>
    <origin xyz="0 0 0 " rpy="${PI*0.0} ${PI*0.0} ${PI*0.0}"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-PI*0.5}" upper="${PI*0.5}" effort="100" velocity="1"/>
  </joint>

  <link name="left_flipper">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/left_flipper2.dae"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/left_flipper2.dae"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${1*mass}"/>
      <inertia	  ixx="1" ixy="0.0" ixz="0.0"	  iyy="1" iyz="0.0"	  izz="1"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="base_link"/>
    <child link="right_flipper"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-PI*0.5}" upper="${PI*0.5}" effort="100" velocity="1"/>
  </joint>
  <link name="right_flipper">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/right_flipper2.dae"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/right_flipper2.dae"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${1*mass}"/>
      <inertia	  ixx="1" ixy="0.0" ixz="0.0"	  iyy="1" iyz="0.0"	  izz="1"/>
    </inertial>
  </link>

  <link name="right_front_wheel">
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="joint3" type="continuous">
    <parent link="left_flipper"/>
    <child link="right_front_wheel"/>
    <origin xyz="${base_link_size_x*1.25} 0 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
    <!--limit lower="${-PI}" upper="${PI}" effort="100" velocity="1"/-->
  </joint>

  <link name="left_front_wheel">
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
      <surface>
          <contact>
            <ode/>
          </contact>
          <friction>
            <ode/>
          </friction>
        </surface>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
    <gravity>1</gravity>
      <velocity_decay>
        <linear>0.000000</linear>
        <angular>0.000000</angular>
      </velocity_decay>
      <self_collide>0</self_collide>

  </link>

  <joint name="joint4" type="continuous">
    <parent link="right_flipper"/>
    <child link="left_front_wheel"/>
    <origin xyz="${-base_link_size_x*1.25} 0 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_rear_wheel">
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
    </visual>
  </link>

  <joint name="joint5" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin xyz="${-base_link_size_x*1.25} ${-base_link_size_y} 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="right_rear_wheel">
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*1.5}' length="0.02"/>
      </geometry>
    </visual>
  </link>

  <joint name="joint6" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin xyz="${base_link_size_x*1.25} ${-base_link_size_y} 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_flipper_wheel">
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*0.9}' length="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*0.9}' length="0.02"/>
      </geometry>
    </visual>
  </link>

  <joint name="joint7" type="continuous">
    <parent link="left_flipper"/>
    <child link="left_flipper_wheel"/>
    <origin xyz="-0.25 0.35 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="right_flipper_wheel">
    <inertial>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <mass value="${0.001*mass}"/>
      <inertia	  ixx="0.1" ixy="0.0" ixz="0.0"	  iyy="0.1" iyz="0.0"	  izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0.00 0 0.0" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*0.9}' length="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.00 0 0.00" rpy="0 ${PI*0.0} 0"/>
      <geometry>
        <cylinder radius='${wheel_radius*0.9}' length="0.02"/>
      </geometry>
    </visual>
  </link>

  <joint name="joint8" type="continuous">
    <parent link="right_flipper"/>
    <child link="right_flipper_wheel"/>
    <origin xyz="0.25 0.35 0 " rpy="${PI*0.0} ${PI*0.5} ${PI*0.0}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <transmission name="tran1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint1">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor1">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="tran2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint2">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor2">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="tran3">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint3">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor3">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="tran4">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint4">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor4">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="tran5">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint5">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor5">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="tran6">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint6">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor6">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="tran7">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint7">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor7">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="tran8">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint8">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor8">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>



</robot>
