// Generated by gencpp from file hector_stair_detection_msgs/PositionAndOrientaion.msg
// DO NOT EDIT!


#ifndef HECTOR_STAIR_DETECTION_MSGS_MESSAGE_POSITIONANDORIENTAION_H
#define HECTOR_STAIR_DETECTION_MSGS_MESSAGE_POSITIONANDORIENTAION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace hector_stair_detection_msgs
{
template <class ContainerAllocator>
struct PositionAndOrientaion_
{
  typedef PositionAndOrientaion_<ContainerAllocator> Type;

  PositionAndOrientaion_()
    : header()
    , directionX(0.0)
    , directionY(0.0)
    , directionZ(0.0)
    , orientation_of_stairs()  {
    }
  PositionAndOrientaion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , directionX(0.0)
    , directionY(0.0)
    , directionZ(0.0)
    , orientation_of_stairs(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _directionX_type;
  _directionX_type directionX;

   typedef float _directionY_type;
  _directionY_type directionY;

   typedef float _directionZ_type;
  _directionZ_type directionZ;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _orientation_of_stairs_type;
  _orientation_of_stairs_type orientation_of_stairs;




  typedef boost::shared_ptr< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> const> ConstPtr;

}; // struct PositionAndOrientaion_

typedef ::hector_stair_detection_msgs::PositionAndOrientaion_<std::allocator<void> > PositionAndOrientaion;

typedef boost::shared_ptr< ::hector_stair_detection_msgs::PositionAndOrientaion > PositionAndOrientaionPtr;
typedef boost::shared_ptr< ::hector_stair_detection_msgs::PositionAndOrientaion const> PositionAndOrientaionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hector_stair_detection_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'hector_stair_detection_msgs': ['/home/somal/catkin_ws/src/hector_visualization/hector_stair_detection_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ae873f11172dc2b64c3df858f4184b8";
  }

  static const char* value(const ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ae873f11172dc2bULL;
  static const uint64_t static_value2 = 0x64c3df858f4184b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hector_stair_detection_msgs/PositionAndOrientaion";
  }

  static const char* value(const ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# hector_stair_detection_msgs\n\
# This message contains,<geometry_msgs::PoseStamped> representing the orientation of the stairs corrosponign to the border; and the direction as Vector\n\
\n\
#Header information\n\
std_msgs/Header header\n\
#direction of staris (vector)\n\
float32 directionX\n\
float32 directionY\n\
float32 directionZ\n\
#orientation per staris\n\
geometry_msgs/PoseStamped orientation_of_stairs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.directionX);
      stream.next(m.directionY);
      stream.next(m.directionZ);
      stream.next(m.orientation_of_stairs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PositionAndOrientaion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hector_stair_detection_msgs::PositionAndOrientaion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "directionX: ";
    Printer<float>::stream(s, indent + "  ", v.directionX);
    s << indent << "directionY: ";
    Printer<float>::stream(s, indent + "  ", v.directionY);
    s << indent << "directionZ: ";
    Printer<float>::stream(s, indent + "  ", v.directionZ);
    s << indent << "orientation_of_stairs: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation_of_stairs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HECTOR_STAIR_DETECTION_MSGS_MESSAGE_POSITIONANDORIENTAION_H
