(cl:defpackage motion_editor_core-msg
  (:use )
  (:export
   "<EXECUTEMOTIONCOMMAND>"
   "EXECUTEMOTIONCOMMAND"
   "<EXECUTEMOTIONGOAL>"
   "EXECUTEMOTIONGOAL"
   "<EXECUTEMOTIONACTIONFEEDBACK>"
   "EXECUTEMOTIONACTIONFEEDBACK"
   "<EXECUTEMOTIONACTION>"
   "EXECUTEMOTIONACTION"
   "<EXECUTEMOTIONACTIONGOAL>"
   "EXECUTEMOTIONACTIONGOAL"
   "<EXECUTEMOTIONRESULT>"
   "EXECUTEMOTIONRESULT"
   "<EXECUTEMOTIONFEEDBACK>"
   "EXECUTEMOTIONFEEDBACK"
   "<EXECUTEMOTIONACTIONRESULT>"
   "EXECUTEMOTIONACTIONRESULT"
  ))

