; Auto-generated. Do not edit!


(cl:in-package motion_editor_core-msg)


;//! \htmlinclude ExecuteMotionFeedback.msg.html

(cl:defclass <ExecuteMotionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ExecuteMotionFeedback (<ExecuteMotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteMotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteMotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_editor_core-msg:<ExecuteMotionFeedback> is deprecated: use motion_editor_core-msg:ExecuteMotionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteMotionFeedback>) ostream)
  "Serializes a message object of type '<ExecuteMotionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteMotionFeedback>) istream)
  "Deserializes a message object of type '<ExecuteMotionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteMotionFeedback>)))
  "Returns string type for a message object of type '<ExecuteMotionFeedback>"
  "motion_editor_core/ExecuteMotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteMotionFeedback)))
  "Returns string type for a message object of type 'ExecuteMotionFeedback"
  "motion_editor_core/ExecuteMotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteMotionFeedback>)))
  "Returns md5sum for a message object of type '<ExecuteMotionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteMotionFeedback)))
  "Returns md5sum for a message object of type 'ExecuteMotionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteMotionFeedback>)))
  "Returns full string definition for message of type '<ExecuteMotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteMotionFeedback)))
  "Returns full string definition for message of type 'ExecuteMotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteMotionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteMotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteMotionFeedback
))
